### ISSUE TITLE
Could not open settings for keywordtracker

### ISSUE THREAD

**Issue by paulharman** [sarahkittyy/KeywordTracker#77]
Stable 240372 (63f8ac7) 
Host 1.0.9020 x86 (38517) 
Windows 10 64-Bit (10.0.22621)

Core v1.9.4

![image](https://github.com/sarahkittyy/KeywordTracker/assets/3407038/02b48dad-4939-4938-b892-ff5430c9e4a7)

[2023-10-26 14:19:10.143][CONSOLE:ERROR] [Addon Settings] Unable to get settings panel for KeywordTracker.
 Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at E.getGuilds (https://discord.com/assets/c59ab0d49e4f72c7144b.js:1:608057)
    at KeywordTracker.buildSettings (betterdiscord://plugins/KeywordTracker.plugin.js:565:55)
    at KeywordTracker.getSettingsPanel (betterdiscord://plugins/KeywordTracker.plugin.js:407:19)
    at betterdiscord/renderer.js:5:86758
    at Object.ej (https://discord.com/assets/e8fd2221603a9472ac4a.js:1:671626)
    at eG (https://discord.com/assets/e8fd2221603a9472ac4a.js:1:671780)
    at https://discord.com/assets/e8fd2221603a9472ac4a.js:1:690089
    at re (https://discord.com/assets/e8fd2221603a9472ac4a.js:1:690188)
    at rt (https://discord.com/assets/e8fd2221603a9472ac4a.js:1:690602)
    at https://discord.com/assets/e8fd2221603a9472ac4a.js:1:696064
[2023-10-26 14:19:11.356][CONSOLE:ERROR] [KeywordTracker] TypeError: Cannot read properties of undefined (reading 'map')

**Comment by paulharman** [comment]
https://betterdiscord.app/

We are aware of issues with Themes and Plugins no longer working.

Discord recently pushed a major update which broke all themes and many plugins. BetterDiscord itself should still be mostly functional but individual settings and options may not be working.

Please be patient while the team works to fix BetterDiscord, and while addon developers work to fix their own Themes and Plugins.

**Comment by paulharman** [comment]
A new version of BetterDiscord has been released (v1.9.5), this update should fix some important pieces required for plugins and themes. You should be able to update through the in-app updater, but if that fails just reinstall BetterDiscord (not repair). You may find that some plugins will start to work again. 

Now that this fix is out, it will take time for developers to fix their plugins and themes so please continue to be patient while they work on updating their addons.

**Comment by Xaenchan** [comment]
Will this work again if Zere's Plugin Library gets updated?

**Comment by sarahkittyy** [comment]
Fixed in latest 1.4.5 update.
