### ISSUE TITLE
Keyword Tracker Plugin keeps crashing and does not work anymore

### ISSUE THREAD

**Issue by AttyRyu** [sarahkittyy/KeywordTracker#91]
stable 328697 (38204c9)
Host 1.0.9163 x64 (52153)
Build Override: N/A
Windows 10 64-bit (10.0.19045)

KeywordTrackerv1.5.4by sawahkitty!~<3

ZeresPluginLibraryv2.0.22by Zerebos

Prior to this incident, the plugin was working perfectly fine. Then, due to some crash that I cannot determine from where (might be from discord or betterdiscord or this plugin), I restarted my PC and opened discord. Discord then installed updates. After this, all the bugs appeared, and keyword tracker plugin wasn't working anymore. 

Here are a list of things I noticed:

1.) The list of keywords I had disappeared.

![image](https://github.com/user-attachments/assets/30398c86-03a2-4697-9eb9-580887b01a82)

2.) The channels I was tracking got messed up, and all channels were toggled "on" even though they should not. 

![image](https://github.com/user-attachments/assets/042f0147-163c-480b-9e12-976afdb36aba)

Then when I toggled it off, this happened:

![image](https://github.com/user-attachments/assets/69172ee2-79e7-4347-b575-d64054fa54a8)

So Discord crashed after that, and restarted. 

This also happened when I tried adding keywords which I need to as the list of keywords disappeared (as in issue no. 1 above).

Conclusion

Keyword Tracker Plugin became unusable. It keeps crashing and does not work anymore with the latest update. It crashes when I try to add a keyword to track. It also crashes when I try to edit channels that I need to monitor for the tracked keywords. On the second crash, the plugin itself disappeared from the settings.

**Comment by AttyRyu** [comment]
In order to have the plugin appear again, I needed to choose repair betterdiscord option when I try to install betterdiscord again. When I launch discord after doing this, I see this prompt:

![image](https://github.com/user-attachments/assets/48871d88-6e5f-4495-9f9c-abdc17dc06c4)

I have the latest version of keywordtracker based on that image. 

I'm 100% positive this has something to do with the latest discord update since it was working a minute before I restarted my PC and reopened discord and after it installed updates.

**Comment by AttyRyu** [comment]
I tried loading keyword tracker with the console open and saw this:

![image](https://github.com/user-attachments/assets/188ae610-3ac7-41d9-b284-2c6400dbef14)

web.faca3c0….js:12 [KeywordTracker] Unable to load data:  SyntaxError: Expected double-quoted property name in JSON at position 13477449 (line 246217 column 2)
    at JSON.parse (<anonymous>)
    at Object.ensurePluginData (renderer.js:5:14572)
    at Object.getPluginData (renderer.js:5:14673)
    at Rn.mn (renderer.js:5:419792)
    at Utilities.loadData (0PluginLibrary.plugin.js:2802:38)
    at Utilities.loadSettings (0PluginLibrary.plugin.js:2830:21)
    at PluginUtilities.loadSettings (0PluginLibrary.plugin.js:2009:107)
    at KeywordTracker.loadSettings (KeywordTracker.plugin.js:878:56)
    at KeywordTracker.onStart (KeywordTracker.plugin.js:577:9)
    at KeywordTracker.start (0PluginLibrary.plugin.js:3666:54)
    at N.startPlugin (renderer.js:5:29059)
    at N.startAddon (renderer.js:5:28852)
    at N.enableAddon (renderer.js:5:7535)
    at N.toggleAddon (renderer.js:5:8334)
    at N.togglePlugin (renderer.js:5:26140)
    at renderer.js:5:92556
    at renderer.js:5:124717
    at Object.ek (web.faca3c0….js:12:946201)
    at eY (web.faca3c0….js:12:946355)
    at web.faca3c0….js:12:964664
    at re (web.faca3c0….js:12:964763)
    at rt (web.faca3c0….js:12:965177)
    at web.faca3c0….js:12:970639
    at oD (web.faca3c0….js:12:1027712)
    at eU (web.faca3c0….js:12:945339)
    at ro (web.faca3c0….js:12:966468)
    at tk (web.faca3c0….js:12:952136)
    at tx (web.faca3c0….js:12:951920)
(anonymous)	@	web.faca3c0….js:12

**Comment by AttyRyu** [comment]
Actually, turns out my json file was just corrupted. I'll mark this as closed myself.
